### ISSUE TITLE
installation issue (make)

### ISSUE THREAD

**Issue by KambizKalhor** [gatech-genemark/MetaGeneMark-2#16]
when trying to install and use in i get the same error, both in my macos and on university ubuntu server.
make -f Makefile.macos
or
make -f Makefile.ubuntu

the error is as follow
g++ -c -o main.o -O2  -Wall -I.  main.cpp 
In file included from main.cpp:32:
In file included from ./sequence_file_2.h:20:
./memory_mapped_file.h:18:10: fatal error: 'boost/iostreams/device/mapped_file.hpp' file not found
   18 | #include <boost/iostreams/device/mapped_file.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [main.o] Error 1

**Comment by moravveji** [comment]
Not sure whether you resolved this by now, but, I had the same issue yesterday, and realized that the path to the Boost `lib` folder and `include` directory are hard-coded in the `Makefile.{macos,ubuntu}`. So, you just need to properly craft that. Also, make sure that you have Perl as a runtime dependency.
Hope this helps.

**Comment by thehelpdeskguy** [comment]
moravveji:

I would like to be able to use your suggestion, but I (sadly) do not know how to implement it.  I am working on a Mac M1 system, Sequoia (15.4.1)

I attempted to 'hardwire' the exact location of the mapped_file.hpp by changing this line in the file:   memory_mapped_file.h
from this:
#include <include/boost/iostreams/device/mapped_file.hpp>
to this
#include </Users/Bio/miniconda3/pkgs/libboost-headers-1.85.0-hce30654_4/include/boost/iostreams/device/mapped_file.hpp>

However, the same error still occurs.  If you have any more suggestions, I would greatly appreciate it.  Thank you.

**Comment by jorvis** [comment]
To fix this you first need to make sure the boost libraries are installed on your system. For me, on Ubuntu, this meant doing this:

`$ sudo apt-get install libboost-all-dev
`
Then I updated my file index and searched for where those files are found:

```
$ sudo updatedb
$ locate mapped_file.hp | grep boost

/usr/include/boost/interprocess/managed_mapped_file.hpp
/usr/include/boost/iostreams/device/mapped_file.hpp
```

I was going to modify the include but actually just tried the make -f command again first. It found the libraries and got past that issue, compiling successfully after also making the change in https://github.com/gatech-genemark/MetaGeneMark-2/pull/3

**Comment by Alex-Lomsadze** [comment]
I am currently clearing a backlog of support tasks. Some questions may be outdated and no longer relevant, but I am reviewing them to close the raised issues.

The previous answer by [jorvis](https://github.com/jorvis) (thank you) should work for Ubuntu users.

This issue is expected and not an error.
For many users, the default Makefiles (Makefile.ubuntu or Makefile.macos) may not function correctly.
MetaGeneMark-2 relies on certain Boost libraries, which you can find at https://www.boost.org. 

Boost libraries are optional on most systems, and their installation location can vary between Linux and macOS.

To resolve this issue, follow these steps: 
1. Install the Boost libraries or the required subset, specifically:
 - headers
 - boost_program_options
 - boost_iostreams 
2. Check if the Boost libraries are accessible through the default configuration. 
If they are not accessible, set the Boost library paths in the Makefile.*.
For a path setup example, see Makefile.ubuntu: "I/usr/include/boost/"

The specific set of commands to achieve the above depends on your operating system.

Boost header files are usually easy and fast to install.
Most frequently, installation issues arise from the compiled, system-dependent library files: "boost_program_options" and "boost_program_options".
Make sure that these two library files are installed on your system.

Best,
Alex Lomsadze
